# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL: "https://blog.syslog.at"
# Basic metadata configuration for your blog.
title: "This is just a test."
languageCode: "en-US"
paginate:  5
theme: "PaperMod"
pluralizelisttitles: false
params:
  disableSpecial1stPost: true
  disableThemeToggle: true
  DateFormat: "Mon, 02 Jan 2006"
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  Author: "Lukas Ertl"
  Email: "le@syslog.at"
  assets:
    disableHLJS: true
    disableScrollBarStyle: true
